# -*- coding: utf-8 -*-
"""llm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jtgP4RVwx6bOWmK520p_fxNvfdLvJXTg
"""

!pip install transformers langchain langchain-community langchain-text-splitters pypdf faiss-cpu torch accelerate sentence-transformers pdfplumber
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_community.llms import HuggingFacePipeline

from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
import torch

loader=PyPDFLoader('/content/agronomy-book.pdf')
doc=loader.load()

splitter=RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200,

)

embedding=HuggingFaceEmbeddings(
   model_name='sentence-transformers/all-MiniLM-L6-v2'

)

vector=FAISS.from_documents(
    documents=doc,
    embedding=embedding
)

vector.save_local('/content/faiss_index')

from huggingface_hub import login

model="meta-llama/Llama-3.2-1B-Instruct"
token=AutoTokenizer.from_pretrained(model)
model=AutoModelForCausalLM.from_pretrained(model,
                                           torch_dtype=torch.float,
                                           device_map='auto')

generate=pipeline(
    task='text-generation',
    model=model,
    tokenizer=token,
    max_length=1000,
    do_sample=True,
    top_k=10,
)

def ask_pdf(question):
    retrieved_docs = vector.similarity_search(
        question,
        k=3
    )

    context = "\n".join(
        [doc.page_content for doc in retrieved_docs]
    )

    prompt = f"""
Answer the question using the context below.

Context:
{context}

Question:
{question}

Answer:
"""

    response = generate(
        prompt,
        max_new_tokens=100,
        do_sample=True,
        temperature=0.3
    )

    return response[0]["generated_text"]

t

while True:
    query = input("Ask: ")

    if query.lower() == "exit":
        break

    answer = ask_pdf(query)
    print(answer)

!pip install flask pyngrok -q

from pyngrok import ngrok
ngrok.set_auth_token('3EdXP7om0eRJz7FpBFd50y2kOOp_87z1qW3UWDhrTjeVKiKwg')

from flask import Flask, request, jsonify
import threading

# LLaMA 3.2 1B — lightweight!
llm = pipeline(
    "text-generation",
    model="meta-llama/Llama-3.2-1B-Instruct",
    torch_dtype=torch.float16,
    device_map="auto"
)

app = Flask(__name__)

@app.route("/ask", methods=["POST"])
def ask():
    question = request.json["question"]

    messages = [{"role": "user", "content": question}]

    output = llm(
        messages,
        max_new_tokens=150,
        do_sample=False
    )

    answer = output[0]["generated_text"][-1]["content"]
    return jsonify({"answer": answer})

public_url = ngrok.connect(5000)
print("🌐 URL:", public_url)

threading.Thread(target=app.run,
                 kwargs={"port": 5000}).start()

import requests

url = "https://goofball-confound-flaring.ngrok-free.dev/ask"  # Updated URL to include /ask endpoint
res = requests.post(url, json={"question": "What is agriculture?"})
print(res.json())